name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 8512546
    - name: Install packages        
      run: |
        sdkmanager "build-tools;33.0.2" "platforms;android-26"        
    - name: Build app
      run: |
        cd doorsofdoom
        mvn --batch-mode clean install
    - name: Build android
      run: |
        cd android-mvn
        mvn --batch-mode clean install android:apk
    - name: Deploy Apk
      uses: actions/upload-artifact@v2
      with:
        name: 'DoorsOfDoom.apk'
        path: android-mvn\target\DoorsOfDoom.apk
